import type { Identity } from "../types";

export const identities: Identity[] = [
  {
    slug: "femme-queen",
    name: "Femme Queen",
    abbreviation: "FQ",
    figure: "FF",
    tagline: "Mujeres trans dentro de Female Figure",
    description: [
      "Femme Queen — FQ — nombra a las mujeres trans dentro de Ballroom. Es Female Figure, no porque la pista les conceda feminidad, sino porque son mujeres y la cultura organiza sus categorías desde esa verdad comunitaria.",
      "Las Femme Queens negras han sido corazón visible de Ballroom desde Harlem: Venus Xtravaganza, Octavia Saint Laurent, Angie Xtravaganza y generaciones de mujeres trans que caminaron Face, Realness, Performance y Sex Siren como afirmación de existencia.",
      "FQ no es drag ni Butch Queen Up in Drag. Una Femme Queen no se viste de mujer para un ball: es mujer. Esa diferencia protege la memoria de las mujeres trans negras que construyeron una cultura donde podían ser coronadas cuando el mundo las negaba.",
    ],
    canWalk: ["face", "runway", "vogue", "realness", "sex-siren", "performance"],
    history: [
      "El término Femme Queen se consolidó cuando las categorías de Ballroom empezaron a separar con más precisión presentación, figura y experiencia. La pista necesitaba distinguir entre mujeres trans, mujeres cis, drag y BQ Up in Drag para juzgar con justicia.",
      "En Harlem, las FQ caminaron categorías donde la belleza, la realness y la feminidad no eran fantasía: eran supervivencia. Pasar como mujer podía significar conseguir trabajo, evitar violencia o moverse por la ciudad con menos peligro.",
      "Las guías contemporáneas de Stephaun Elite Wallace y escenas como House of Luna sostienen esa distinción: FQ pertenece a Female Figure, con categorías propias como FQ Face, FQ Realness y FQ Performance.",
    ],
    relatedCategories: ["femme-queen-face", "femme-queen-realness", "femme-queen-vogue-fem", "femme-queen-sex-siren"],
  },
  {
    slug: "butch-queen",
    name: "Butch Queen",
    abbreviation: "BQ",
    figure: "MF",
    tagline: "El mariquita de Ballroom: hombre gay dentro de Male Figure",
    description: [
      "Butch Queen — BQ — es el hombre gay o bisexual cis dentro de Ballroom. En lenguaje de la escena, es el mariquita que camina como Male Figure: puede servir BQ Face, BQ Realness, BQ Sex Siren, Vogue y otras categorías masculinas.",
      "Butch Queen no significa twister automáticamente. BQ es la figura; twister es una modalidad de categoría/performance cuando ese BQ camina Vogue Femme/Twisters. El BQ existe aunque no voguee fem.",
      "Tampoco es Drag ni Butch Queen Up in Drag. Un Butch Queen puede presentarse masculino de forma cotidiana y, para ciertos balls, decidir caminar Up in Drag. En ese momento entra a Female Figure para esa presentación específica.",
    ],
    canWalk: ["butch-queen-face", "vogue", "realness", "sex-siren", "body", "runway"],
    history: [
      "Butch Queen cristalizó en Harlem como una de las figuras más centrales de Ballroom. Los hombres gay negros que no caminaban como mujeres necesitaban categorías masculinas propias, separadas de Femme Queens, Butches y Drags.",
      "Willi Ninja encarna la potencia BQ: hombre gay negro, Male Figure, maestro de voguing, figura capaz de transformar la pista sin convertirse en Female Figure.",
      "La precisión importa porque evita confusiones: BQ es el mariquita; Twister es el BQ en Vogue Femme/Twisters; Butch Queen Up in Drag es el BQ que para un ball específico se presenta en fem y compite como Female Figure.",
    ],
    relatedCategories: ["butch-queen-face", "butch-queen-vogue-fem-twister", "realness-with-a-twist", "male-figure-sex-siren"],
  },
  {
    slug: "twister",
    name: "Twister",
    figure: "MF",
    tagline: "Butch Queen que camina Vogue Femme/Twisters",
    description: [
      "Twister no es una identidad separada: es un Butch Queen en una categoría específica. El twister es el BQ que camina Vogue Femme/Twisters, llevando la técnica, la dramatización y los elementos fem del voguing desde una base BQ.",
      "La diferencia es simple: Butch Queen es quién eres en la estructura de Ballroom; Twister es cómo caminas una categoría. Un BQ puede ser BQ Face, BQ Realness o BQ Sex Siren sin ser twister.",
      "En algunas conversaciones se dice que el twister «camina realness» porque la categoría puede jugar con pasar, sorprender y luego torcer la presentación hacia Vogue Fem. Pero la clave es que sigue siendo BQ: no se vuelve Drag, FQ ni Female Figure.",
    ],
    canWalk: ["butch-queen-vogue-fem-twister", "realness-with-a-twist"],
    history: [
      "Vogue Femme/Twisters se formalizó cuando el voguing se ramificó y la pista necesitó nombrar a los BQ que dominaban elementos fem sin competir contra Femme Queens.",
      "La categoría conserva una tensión creativa central de Ballroom: masculinidad BQ, técnica fem, teatralidad y lectura de pista. Esa tensión es performance, no cambio de identidad.",
      "Por eso la categoría es Male Figure aunque use vocabulario fem. El twister es BQ con chops específicos en Vogue Femme/Twisters.",
    ],
    relatedCategories: ["butch-queen-vogue-fem-twister", "realness-with-a-twist"],
  },
  {
    slug: "drag",
    name: "Drag",
    figure: "FF",
    tagline: "Persona que camina en fem de forma sostenida en Ballroom",
    description: [
      "En Ballroom, Drag es la persona que va a los balls de mujer de forma sostenida: porque está en transición hacia Femme Queen, porque explora feminidad, o porque le gusta vivir esa presentación en la escena.",
      "Drag entra en Female Figure. La diferencia con Femme Queen es que FQ es mujer trans; Drag es una presentación fem dentro de Ballroom que no debe borrar ni reemplazar a las mujeres trans.",
      "También se diferencia de Butch Queen Up in Drag: Drag suele sostener esa presentación como forma habitual de caminar la escena; BQ Up in Drag es un Butch Queen que se viste de mujer para ciertos balls o categorías específicas.",
    ],
    canWalk: ["drag-realness", "runway", "face", "sex-siren", "performance"],
    history: [
      "El drag negro antecede a Ballroom organizado y fue parte de los balls desde antes de la House of LaBeija. Pero Ballroom desarrolló su propio lenguaje para separar Drag, Femme Queen y Butch Queen Up in Drag.",
      "Esa separación protege la justicia competitiva: una persona Drag en Female Figure no se evalúa igual que una FQ, ni igual que un BQ que solo ocasionalmente sube en drag.",
      "En la escena contemporánea, Drag sigue siendo parte de Female Figure y puede aparecer en Realness, Runway, Best Dressed, Performance o categorías FF según el flyer.",
    ],
    relatedCategories: ["drag-realness", "runway", "sex-siren", "performance"],
  },
  {
    slug: "butch-queen-up-in-drag",
    name: "Butch Queen Up in Drag",
    abbreviation: "BQUID",
    figure: "FF",
    tagline: "Butch Queen que para ciertos balls se presenta en fem",
    description: [
      "Butch Queen Up in Drag es un Butch Queen que, para ciertos balls o categorías, se viste y se presenta como mujer. Sigue siendo BQ como figura comunitaria de base, pero en esa presentación entra en Female Figure.",
      "La clave está en la frecuencia y la intención: Drag es quien va a los balls de mujer de forma sostenida; Butch Queen Up in Drag es el BQ que sube en drag para una ocasión, una categoría o una fantasía específica.",
      "Esta distinción es importante porque ordena la competencia sin confundirla con Femme Queen. Una FQ no es BQ Up in Drag. Una persona Drag no es automáticamente BQ Up in Drag. Ballroom necesita esos matices para juzgar con respeto.",
    ],
    canWalk: ["butch-queen-up-in-drag-realness", "runway", "face", "sex-siren", "performance"],
    history: [
      "Butch Queen Up in Drag aparece en Ballroom como una forma de reconocer al BQ que puede ejecutar ilusión fem sin abandonar su lugar de BQ en la cultura.",
      "Históricamente, muchas categorías mezclaban drag, FQ y BQUID de forma imprecisa. La escena fue afinando el lenguaje para proteger a las Femme Queens y para evaluar la presentación del BQ up in drag entre pares.",
      "En Female Figure, BQUID compite por la credibilidad y la estética de su presentación fem, pero su lectura comunitaria sigue entendiendo que la base es Butch Queen.",
    ],
    relatedCategories: ["butch-queen-up-in-drag-realness", "runway", "sex-siren"],
  },
  {
    slug: "female-figure",
    name: "Female Figure",
    abbreviation: "FF",
    figure: "FF",
    tagline: "Paraguas femenino: FQ, Women, Drag y BQ Up in Drag",
    description: [
      "Female Figure — FF — es el paraguas de presentación femenina en Ballroom. Incluye Femme Queens, Women, Drag y Butch Queen Up in Drag.",
      "FF no borra diferencias internas. Una FQ, una Woman, una persona Drag y un BQ Up in Drag pueden entrar bajo Female Figure, pero no son lo mismo ni deben juzgarse siempre con los mismos criterios.",
      "La función de FF es organizar la pista: saber quién camina qué categoría, bajo qué presentación y con qué reglas. Es estructura competitiva, no etiqueta única para todas las experiencias.",
    ],
    canWalk: ["face", "runway", "vogue", "realness", "sex-siren", "performance"],
    history: [
      "Female Figure se formalizó cuando Ballroom dejó de tratar la feminidad en la pista como una sola cosa. Harlem necesitó distinguir entre mujeres trans, mujeres cis, drag y BQ Up in Drag.",
      "Esa precisión es parte de la memoria negra de Ballroom: categorías justas para experiencias distintas, sin borrar a quienes construyeron la cultura.",
      "Hoy FF sigue siendo clave para entender Face, Realness, Sex Siren, Runway y Performance en balls con categorías especializadas.",
    ],
    relatedCategories: ["face", "runway", "realness", "sex-siren"],
  },
  {
    slug: "male-figure",
    name: "Male Figure",
    abbreviation: "MF",
    figure: "MF",
    tagline: "Paraguas masculino: BQ, Butch y Trans Man",
    description: [
      "Male Figure — MF — agrupa las figuras que caminan con presentación masculina: Butch Queens, Butches y Trans Men.",
      "MF permite organizar categorías masculinas sin confundir experiencias. Un BQ, una butch y un trans man pueden compartir paraguas, pero cada uno tiene reglas específicas en categorías como Realness o Face.",
      "La pista evalúa presentación y pertenencia comunitaria. Por eso MF es estructura de competencia, no una identidad única.",
    ],
    canWalk: ["face", "runway", "vogue", "realness", "sex-siren", "body", "performance"],
    history: [
      "Male Figure cristalizó junto con Female Figure cuando las categorías de Ballroom se hicieron más precisas en Harlem.",
      "La formalización permitió espacios como BQ Face, Butch Realness y Transmale Realness, evitando que figuras distintas compitieran bajo criterios injustos.",
      "Hoy MF sigue siendo uno de los marcos centrales de la pista.",
    ],
    relatedCategories: ["face", "runway", "vogue", "realness", "sex-siren", "body"],
  },
  {
    slug: "butch",
    name: "Butch",
    figure: "MF",
    tagline: "Mujeres masculinas dentro de Male Figure",
    description: [
      "Butch nombra a mujeres cis de presentación masculina dentro de Ballroom. Compiten bajo Male Figure porque la pista evalúa su presentación masculina, no porque niegue que sean mujeres.",
      "Butch no es Butch Queen. La butch es mujer masculina; el BQ es hombre gay cis. Esa diferencia ordena categorías como Butch Realness, Butch Face y MF Sex Siren.",
      "Las butches negras han sido competidoras, mothers y referentes de estilo en Ballroom, defendiendo una masculinidad femenina propia.",
    ],
    canWalk: ["face", "runway", "realness", "sex-siren", "body", "performance"],
    history: [
      "Las butches han estado en Ballroom desde los primeros balls de Harlem, aunque su codificación formal llegó con la especialización de categorías.",
      "Butch Realness evalúa la capacidad de pasar como hombre en contextos específicos, una habilidad con peso social para muchas mujeres masculinas negras.",
      "La categoría protege un espacio que no debe confundirse con BQ ni con Trans Man.",
    ],
    relatedCategories: ["butch-realness", "face", "body", "sex-siren"],
  },
  {
    slug: "trans-man",
    name: "Trans Man",
    figure: "MF",
    tagline: "Hombres trans dentro de Male Figure",
    description: [
      "Trans Man nombra a hombres trans dentro de Ballroom. Es Male Figure, con categorías que reconocen su experiencia específica, como Trans Man Realness.",
      "No es Butch ni Butch Queen. La categoría existe para evitar que hombres trans tengan que competir bajo nombres que no reconocen su realidad.",
      "Trans Man puede caminar MF Sex Siren, MF Body, Trans Man Realness, Vogue Femme/Twisters y categorías OTA según el flyer.",
    ],
    canWalk: ["trans-man-realness", "vogue", "sex-siren", "body", "runway", "performance"],
    history: [
      "Los hombres trans participaron de Ballroom mucho antes de que la escena les diera visibilidad suficiente. La formalización de Trans Man Realness corrigió parte de esa invisibilidad.",
      "Las guías contemporáneas separan Trans Man de Butch y BQ, sosteniendo una competencia más justa y respetuosa.",
      "Hoy los hombres trans negros reclaman lugar propio dentro de una cultura que sigue aprendiendo a nombrarlos con precisión.",
    ],
    relatedCategories: ["trans-man-realness", "vogue", "body", "sex-siren"],
  },
  {
    slug: "women",
    name: "Women",
    figure: "FF",
    tagline: "Mujeres cis dentro de Female Figure",
    description: [
      "Women nombra a mujeres cis dentro de Female Figure. No son Femme Queens, Drag ni BQ Up in Drag: son mujeres cis con categorías propias.",
      "Women's Face, Women's Vogue y categorías FF permiten que mujeres cis compitan entre pares sin borrar a FQ ni mezclar criterios de presentación.",
      "Las mujeres cis negras han sido fundadoras, mothers y competidoras de Ballroom; su lugar en Female Figure es histórico, no secundario.",
    ],
    canWalk: ["womens-face", "womens-vogue", "runway", "sex-siren", "performance"],
    history: [
      "Mujeres cis negras como Crystal LaBeija, Pepper LaBeija y Dorian Corey fueron arquitectas de Ballroom.",
      "La categoría Women se formalizó para reconocer esa experiencia dentro de FF con reglas propias.",
      "Hoy Women sigue siendo parte esencial de la pista y de las Houses.",
    ],
    relatedCategories: ["womens-face", "womens-vogue", "runway", "sex-siren"],
  },
  {
    slug: "non-binary-ota",
    name: "Non-Binary / OTA",
    figure: "OTA",
    tagline: "Open To All y figuras fuera de la binariedad",
    description: [
      "Non-Binary / OTA nombra el espacio abierto para personas no binarias, GNC y competidores cuya presentación no encaja de forma limpia en FF o MF.",
      "OTA no significa sin reglas: cada categoría define qué evalúa, pero no restringe la entrada por figura de la misma manera que FF o MF.",
      "La expansión OTA continúa la lógica original de Ballroom: crear pista para quienes el mundo deja fuera.",
    ],
    canWalk: ["ota", "bizarre", "performance", "hands-performance", "best-dressed", "labels", "runway"],
    history: [
      "OTA se formalizó como respuesta a la necesidad de categorías abiertas dentro de una estructura cada vez más especializada.",
      "El lenguaje contemporáneo de GNC y no binario actualiza prácticas que Ballroom ya sostenía: género como performance, presentación y comunidad.",
      "Hoy OTA es puerta de entrada y espacio de innovación en escenas globales.",
    ],
    relatedCategories: ["ota", "bizarre", "performance", "hands-performance"],
  },
];
