import type { Identity } from "../types";

export const identities: Identity[] = [
  {
    slug: "femme-queen",
    name: "Femme Queen",
    abbreviation: "FQ",
    figure: "FF",
    tagline: "Mujeres trans en el centro de la pista negra",
    description: [
      "Femme Queen — abreviado FQ — es la identidad de Ballroom que reconoce a las mujeres trans dentro de la cultura. Aunque históricamente se clasificaba bajo el paraguas Male Figure por convenciones heredadas de una época en que el lenguaje de género en Harlem era más rígido, la comprensión contemporánea — codificada por historiadores como Stephaun Elite Wallace de la Legendary House of Blahnik y adoptada por casas como la House of Luna — sitúa a las Femme Queens firmemente dentro de Female Figure: son mujeres, y la pista debe tratarlas como tales.",
      "En Harlem, las Femme Queens fueron desde el origen el corazón visible de Ballroom. Venus Xtravaganza, Octavia Saint Laurent, Angie Xtravaganza — mujeres trans negras cuya belleza, ambición y dolor aparecieron en Paris Is Burning — caminaron categorías que les pertenecían no por concesión sino por derecho. Su presencia en Face, Realness y Vogue no era performance decorativa: era la afirmación de que las mujeres trans negras existen, son hermosas, son creíbles y merecen ser coronadas.",
      "Las categorías específicas para Femme Queen — Femme Queen Face, Femme Queen Realness, Femme Queen Performance — no son espacios de segregación sino de reconocimiento. Según las guías de Stephaun Elite Wallace, una Femme Queen en Realness debe ser una mujer trans (MTF), no una drag queen ni una mujer cis. La «realness» evalúa la capacidad de «pasar» como mujer en contextos que históricamente negaron la existencia de las mujeres trans negras. Esa evaluación tiene peso existencial: en la calle, pasar podía significar sobrevivir.",
      "Ser Femme Queen en Ballroom es navegar una intersección compleja de género, raza y clase. Las Femme Queens negras enfrentaron — y enfrentan — violencia transfóbica, rechazo familiar, criminalización y la epidemia de SIDA que arrancó generaciones enteras de la escena. Ballroom les dio apellido, categoría, trofeo y familia. La House of Xtravaganza, la House of LaBeija y docenas de casas acogieron hijas trans que el mundo había expulsado.",
      "Entender Femme Queen requiere rechazar la lógica cisnormativa que confunde identidad con presentación o con anatomía. Una Femme Queen no «se viste de mujer» — es mujer. La pista de Ballroom, cuando funciona con integridad, refleja esa verdad. Las guías contemporáneas de categorías — desde la House of Luna hasta escenas kiki globales — consolidan lo que las madres de Harlem siempre supieron: las Femme Queens son Female Figure, y Female Figure sin Femme Queens no sería Ballroom.",
    ],
    canWalk: [
      "face",
      "runway",
      "vogue",
      "realness",
      "sex-siren",
      "best-dressed",
      "performance",
    ],
    history: [
      "El término Femme Queen emerge de la jerga negra queer de Harlem en la década de 1970, cuando las categorías de Ballroom comenzaron a especializarse para reflejar la diversidad real de quienes caminaban la pista. Antes de esa codificación, las mujeres trans competían en espacios ambiguos — a veces agrupadas con drag queens, a veces excluidas por criterios que no reconocían su identidad.",
      "La formalización de categorías Femme Queen respondió a una necesidad de la comunidad negra trans: espacios donde no tuvieran que competir contra hombres cis en drag ni ser confundidas con mujeres cis. Femme Queen Face, Femme Queen Realness y Femme Queen Performance crearon pistas propias con criterios que honraban la experiencia trans femenina.",
      "Stephaun Elite Wallace — icono de Ballroom, historiador y miembro de la Legendary House of Blahnik — ha documentado y sistematizado estas distinciones con rigor que trasciende regiones. Sus guías de categorías, adoptadas por la House of Luna y referenciadas en escenas de todo el continente, clarifican que Femme Queen pertenece a Female Figure y que las categorías FQ son exclusivas para mujeres trans.",
      "Hoy, las Femme Queens negras siguen siendo referentes en escenas globales — desde Nueva York hasta Bogotá, desde São Paulo hasta París. Pero toda Femme Queen que camina una pista camina sobre el legado de Venus, de Octavia, de las hijas de Crystal LaBeija que dijeron «soy mujer» cuando el mundo decía lo contrario.",
    ],
    relatedCategories: ["face", "realness", "vogue", "sex-siren"],
  },
  {
    slug: "butch-queen",
    name: "Butch Queen",
    abbreviation: "BQ",
    figure: "MF",
    tagline: "Hombres gay y bisexuales en la arquitectura masculina de Ballroom",
    description: [
      "Butch Queen — BQ — designa a hombres cisgénero gay, bisexuales o same-gender-loving dentro de la cultura de Ballroom. Es una identidad Male Figure: compite en categorías masculinas, camina con la energía que la pista asocia a lo masculino, y ocupa un lugar central en la historia negra de Harlem como uno de los pilares demográficos del movimiento.",
      "El término «butch» aquí no describe presentación femenina sino una tradición lingüística negra queer: «butch queen» distingue al hombre gay de la butch (mujer masculina), de la femme queen (mujer trans) y de la drag queen (hombre cis en fem). Es taxonomía comunitaria, no etiqueta peyorativa. En la boca de una Mother de Harlem, «butch queen» es reconocimiento de pertenencia.",
      "Las categorías Butch Queen — BQ Face, BQ Realness, BQ Vogue, BQ Sex Siren — tienen reglas explícitas codificadas por Stephaun Elite Wallace: el competidor debe ser hombre cisgénero gay/bi, no mujer trans ni mujer butch ni hombre trans. Esas distinciones no son gatekeeping arbitrario: son el mecanismo por el cual Ballroom organiza la competencia de forma justa dentro de identidades específicas.",
      "Willi Ninja — padre de la House of Ninja, maestro de voguing, figura legendaria de Ballroom — encarnó la Butch Queen en su máxima expresión. No era drag queen ni se presentaba como mujer, pero dominaba la pista con una masculinidad negra queer que redefinió lo posible. Las Butch Queens negras han sido voguers, commentatoras, madres, padres y arquitectos de la cultura.",
      "Ser Butch Queen en Ballroom es habitar la intersección de negritud, homosexualidad y performance. En una sociedad que hipersexualiza a los hombres negros mientras niega su humanidad queer, la pista ofrece un espacio donde servir rostro, caminar con autoridad y voguear con precisión es acto de afirmación. Las Butch Queens no compiten a pesar de ser negras y gay — compiten como negras y gay, y la pista las coronan por ello.",
    ],
    canWalk: [
      "face",
      "runway",
      "vogue",
      "realness",
      "sex-siren",
      "body",
      "ota",
      "performance",
      "best-dressed",
    ],
    history: [
      "Butch Queen como categoría identitaria cristalizó en la década de 1970 en Harlem, cuando los balls evolucionaron de concursos drag generalizados hacia sistemas sofisticados de categorías por identidad. Los hombres gay negros que no hacían drag pero querían competir necesitaban un espacio propio — y Butch Queen fue la respuesta.",
      "La categoría Butch Queen Up in Drags Realness — distinta de Drag Queen Realness — reconoce al BQ que se presenta en fem sin dejar de ser butch queen. Es la línea fina entre identidad y performance que Ballroom navega con precisión: el BQ en drags sigue siendo BQ, no DQ.",
      "Las guías de Stephaun Elite Wallace, referenciadas por la House of Luna y adoptadas en escenas kiki internacionales, establecen los criterios actuales para categorías BQ. Su trabajo como historiador de Ballroom ha preservado distinciones que de otra forma se habrían diluido en la apropiación mainstream.",
      "En la escena contemporánea, las Butch Queens negras siguen dominando Vogue Femme/Twisters, Old Way, New Way y categorías OTA. Desde Harlem hasta Medellín, el BQ sigue siendo la identidad más numerosa en muchos balls — y la más visible en la cultura popular gracias a figuras como Willi Ninja.",
    ],
    relatedCategories: ["face", "vogue", "realness", "sex-siren", "body"],
  },
  {
    slug: "butch",
    name: "Butch",
    figure: "MF",
    tagline: "Mujeres masculinas que reclaman la pista como Male Figure",
    description: [
      "Butch — dentro de Ballroom — designa a mujeres cisgénero de presentación masculina: lesbianas, bisexuales y same-gender-loving women que compiten bajo el paraguas Male Figure. Es una de las identidades más malinterpretadas fuera de la cultura, porque el lenguaje mainstream confunde «butch» con «hombre» o con «mujer que imita hombre». En Ballroom, butch es identidad propia con categorías, respeto y historia.",
      "La clasificación de butch bajo Male Figure no niega que sean mujeres — reconoce que su presentación en la pista es masculina y que compiten en categorías masculinas. Butch Face, Butch Realness, Butch Vogue: cada una evalúa la capacidad de la competidora de servir rostro, pasar como hombre o dominar el baile desde una masculinidad femenina. Es Female Figure en cuerpo, Male Figure en pista.",
      "Las guías de Stephaun Elite Wallace son explícitas: Butch Realness es para mujeres cis butch, no para hombres cis ni hombres trans. La «realness» evalúa la capacidad de «pasar» como hombre heterosexual — una habilidad que muchas mujeres butch negras desarrollaron por necesidad en espacios hostiles. En la pista, esa supervivencia cotidiana se transforma en arte y se celebra con trofeos.",
      "Las butch negras en Ballroom han sido competidoras ferozmente respetadas, mothers de casas, y referentes de estilo. Su presencia desafía tanto la heteronormatividad como la feminidad normativa impuesta a las mujeres negras. Caminar como butch en Harlem no era escapar de la negritud ni de la feminidad — era habitar ambas desde una posición de poder masculino auténtico.",
      "Entender butch requiere respetar la autonomía de las mujeres negras sobre su propia presentación. Una butch no «quiere ser hombre» — quiere ser ella misma, y Ballroom le da categoría para demostrarlo. Las escenas contemporáneas que adoptan las guías de la House of Luna y de Stephaun Elite Wallace mantienen esa distinción con claridad que protege el espacio butch de la apropiación.",
    ],
    canWalk: ["face", "runway", "vogue", "realness", "sex-siren", "body", "performance"],
    history: [
      "Las butch han estado en Ballroom desde los primeros balls de Harlem, aunque la codificación explícita de «Butch» como categoría identitaria tardó en formalizarse. En la década de 1970 y 1980, a medida que las categorías se multiplicaron, las mujeres masculinas exigieron espacios propios separados de las Femme Queens y de las Women.",
      "Butch Realness emergió como una de las categorías más profundas de Ballroom: evaluar qué tan convincentemente una mujer negra butch puede «pasar» como hombre en contextos que niegan su lesbianismo y su masculinidad. Es Realness en su sentido más existencial — la calle y la pista reflejándose mutuamente.",
      "Stephaun Elite Wallace documentó las reglas butch con la precisión que la comunidad necesitaba para sostener balls justos. Sus guías — adoptadas por la House of Luna — especifican que Butch Face es exclusiva para mujeres cis butch, no para drag queens ni femme queens.",
      "Hoy, las butch negras compiten en escenas globales con la misma autoridad que sus ancestras en Harlem. La categoría sigue siendo Male Figure, la identidad sigue siendo femenina, y la pista sigue siendo un espacio donde las mujeres negras masculinas son visibles, respetadas y coronadas.",
    ],
    relatedCategories: ["face", "realness", "vogue", "body", "sex-siren"],
  },
  {
    slug: "drag-queen",
    name: "Drag Queen",
    abbreviation: "DQ",
    figure: "FF",
    tagline: "Hombres cis en fem: performance, realness y Female Figure",
    description: [
      "Drag Queen — DQ — designa a hombres cisgénero que se visten y presentan como mujeres dentro de Ballroom. Es Female Figure: compite en categorías femeninas, camina con presentación femenina, y ocupa un lugar distinto y esencial dentro de la taxonomía de identidades que separa performance de identidad.",
      "La distinción entre Drag Queen y Femme Queen es fundamental en Ballroom y está codificada con precisión en las guías de Stephaun Elite Wallace: la DQ es hombre cis en cross-dressing; la FQ es mujer trans. Confundir ambas identidades no es error inocente — es borrar la existencia de las mujeres trans negras que construyeron Ballroom. Las categorías Drag Queen Realness y Femme Queen Realness existen precisamente para mantener esa frontera.",
      "Drag Queen Realness evalúa la capacidad del competidor de «pasar» como mujer — no como mujer trans, sino como mujer cis en el imaginario heteronormativo. Es performance de género en su forma más sofisticada: el DQ negro que convence a los jueces de que podría ser la mujer del anuncio, la ejecutiva, la pretty girl. En Harlem, esa habilidad tenía valor de supervivencia y de espectáculo.",
      "Las drag queens negras han sido parte de Ballroom desde antes de que existiera el término «Ballroom». El drag negro en Harlem — en clubes, en fiestas, en concursos — fue antecedente directo de los balls organizados por Crystal LaBeija. Pero Ballroom no es drag pageant: es sistema de Houses, categorías, identidades y competencia con reglas propias que la drag queen debe aprender para competir con integridad.",
      "Ser Drag Queen en Ballroom es habitar la tensión entre identidad masculina y presentación femenina sin que una anule a la otra. El DQ sigue siendo Male Figure en identidad biográfica pero Female Figure en la pista — y esa dualidad es parte de lo que hace a Ballroom un laboratorio de género negro sin paralelo en la cultura occidental.",
    ],
    canWalk: [
      "realness",
      "runway",
      "face",
      "sex-siren",
      "performance",
      "best-dressed",
      "bizarre",
    ],
    history: [
      "El drag negro en Harlem precede a Ballroom como movimiento organizado, pero las drag queens fueron parte integral de los primeros balls de la House of LaBeija. Crystal LaBeija misma era drag queen antes de fundar el universo de Houses — y su experiencia de exclusión en concursos drag blancos fue el catalizador del movimiento.",
      "La codificación de Drag Queen como identidad separada de Femme Queen respondió a décadas de confusión y borradura. Las mujeres trans negras competían en categorías de drag; las drag queens competían en categorías de mujeres. La especialización de categorías en la década de 1980 clarificó fronteras que protegen identidades distintas.",
      "Las guías de Stephaun Elite Wallace — referenciadas por la House of Luna — establecen que Drag Queen Realness es exclusiva para hombres cis en cross-dressing, no para mujeres trans ni mujeres cis. Esa regla, repetida en balls de todo el mundo, es acto de respeto a las Femme Queens.",
      "En la escena contemporánea, las drag queens negras siguen caminando Realness, Sex Siren FF y Performance con la creatividad que caracteriza al drag negro. RuPaul's Drag Race popularizó el drag blanco; Ballroom preserva el drag negro con sus reglas, su historia y su memoria de Harlem intacta.",
    ],
    relatedCategories: ["realness", "runway", "sex-siren", "performance"],
  },
  {
    slug: "female-figure",
    name: "Female Figure",
    abbreviation: "FF",
    figure: "FF",
    tagline: "El paraguas femenino de Ballroom: FQ, Women y Drag Queen",
    description: [
      "Female Figure — FF — es el término paraguas de Ballroom que agrupa todas las identidades de presentación femenina en la pista: Femme Queens (mujeres trans), Women (mujeres cis) y Drag Queens (hombres cis en fem). No es identidad competitiva en sí misma sino sistema clasificatorio que organiza categorías, reglas y espacios.",
      "El concepto de Female Figure responde a una necesidad práctica de Ballroom: muchas categorías evalúan presentación femenina — Face, Runway, Sex Siren, Vogue — y necesitan saber quién compite con quién. FF agrupa a quienes caminan «como mujer» en la pista, independientemente de su identidad biográfica. Es taxonomía de performance, no reducción existencial.",
      "Stephaun Elite Wallace codificó Female Figure con la claridad que la escena global necesitaba: «trans women, cisgendered women, and drag queens» — tres identidades distintas bajo un paraguas de presentación. Las guías de la House of Luna adoptan esta definición y la aplican en categorías como FF Sex Siren, donde la presentación femenina es el criterio central.",
      "Entender FF requiere entender que Ballroom opera con dos registros simultáneos: identidad comunitaria (Femme Queen, Woman, Drag Queen) y figura de pista (Female Figure, Male Figure, OTA). Una Femme Queen es FF en la pista aunque su historia biográfica sea distinta de una Woman o una Drag Queen. Las subcategorías — Femme Queen Face vs. Women's Face vs. Drag Queen Realness — respetan esas diferencias dentro del paraguas.",
      "Female Figure sin sus subidentidades sería vacío. FF es el techo; Femme Queen, Women y Drag Queen son las habitaciones. Stephaun Elite Wallace y las casas que adoptan sus guías — House of Luna, House of Blahnik, escenas kiki globales — mantienen esa arquitectura porque sin ella, la competencia pierde integridad y las identidades pierden protección.",
    ],
    canWalk: [
      "face",
      "runway",
      "vogue",
      "realness",
      "sex-siren",
      "best-dressed",
      "performance",
    ],
    history: [
      "El lenguaje de «figure» en Ballroom emerge de la necesidad de clasificar presentación en la pista sin reducir identidad a anatomía. En Harlem, donde las identidades trans, queer y de drag convivían en los mismos balls, se necesitaba vocabulario que organizara la competencia sin borrar diferencias.",
      "Female Figure se formalizó a medida que las categorías se especializaron en la década de 1980. Antes, «mujer en la pista» podía significar cosas distintas para distintas personas. FF creó el paraguas; Femme Queen, Women y Drag Queen crearon las distinciones.",
      "Stephaun Elite Wallace — historiador, icono y miembro de la Legendary House of Blahnik — sistematizó FF en guías de categorías que hoy son referencia en escenas de Seattle, Latinoamérica y Europa. Su trabajo preserva la lógica negra de Ballroom para generaciones que no vivieron Harlem.",
      "Hoy, Female Figure sigue siendo el marco organizativo esencial de cualquier ball con categorías especializadas. Sin FF, no hay Femme Queen Face ni Women's Vogue ni Drag Queen Realness — hay caos, injusticia y borradura de identidades trans negras.",
    ],
    relatedCategories: ["face", "runway", "vogue", "realness", "sex-siren"],
  },
  {
    slug: "male-figure",
    name: "Male Figure",
    abbreviation: "MF",
    figure: "MF",
    tagline: "El paraguas masculino: BQ, Butch y Trans Man",
    description: [
      "Male Figure — MF — es el término paraguas de Ballroom que agrupa todas las identidades de presentación masculina en la pista: Butch Queens (hombres gay cis), Butch (mujeres masculinas cis) y Trans Man (hombres trans). Como Female Figure, no es identidad competitiva sino sistema clasificatorio que organiza categorías masculinas.",
      "La lógica de MF es paralela a FF: quienes caminan «como hombre» en la pista compiten en categorías masculinas, independientemente de su identidad biográfica. Un Butch Queen, una butch y un trans man compiten en MF Sex Siren, MF Body, MF Runway — pero cada uno tiene subcategorías propias que respetan su experiencia específica.",
      "Stephaun Elite Wallace define Male Figure como «Butch queens, butch women, and transgender men» — tres identidades bajo un paraguas de presentación masculina. Las guías de la House of Luna aplican esta definición en categorías como MF Sex Siren y MF Catboy, donde la presentación masculina es criterio central.",
      "La inclusión de butch bajo MF — mujeres que compiten en categorías masculinas — es una de las características más distintivas de la taxonomía de Ballroom. Fuera de la cultura, parece contradictorio; dentro, es coherencia comunitaria: la pista evalúa presentación, y la butch presenta masculino. Las subcategorías Butch Face y Butch Realness protegen su espacio dentro del paraguas.",
      "Male Figure es el complemento necesario de Female Figure para que Ballroom funcione como sistema. Sin MF, no hay BQ Face, Butch Realness ni Transmale Realness. Stephaun Elite Wallace y las casas que adoptan sus guías mantienen esa arquitectura como acto de preservación de la lógica negra de categorías.",
    ],
    canWalk: [
      "face",
      "runway",
      "vogue",
      "realness",
      "sex-siren",
      "body",
      "performance",
    ],
    history: [
      "Male Figure como concepto organizativo cristalizó junto a Female Figure cuando Ballroom evolucionó de concursos generalizados hacia sistemas de categorías por identidad y presentación. En Harlem, los hombres gay, las mujeres butch y los hombres trans compartían pista pero necesitaban espacios diferenciados.",
      "La formalización de MF permitió categorías como BQ Face (solo hombres gay cis), Butch Realness (solo mujeres butch cis) y Transmale Realness (solo hombres trans) — cada una con criterios que protegen la integridad competitiva.",
      "Stephaun Elite Wallace documentó MF con el rigor que escenas fuera de Nueva York necesitaban para organizar balls justos. Sus guías, adoptadas por la House of Luna, son referencia en la costa oeste, Latinoamérica y escenas kiki europeas.",
      "Hoy, Male Figure sigue siendo el marco bajo el cual compiten la mayoría de categorías masculinas de Ballroom. Sin MF, la pista pierde estructura — y las identidades butch y trans masculinas pierden el espacio que Harlem les garantizó.",
    ],
    relatedCategories: ["face", "runway", "vogue", "realness", "sex-siren", "body"],
  },
  {
    slug: "trans-man",
    name: "Trans Man",
    figure: "MF",
    tagline: "Hombres trans bajo Male Figure en la pista negra",
    description: [
      "Trans Man — o transman en la jerga de Ballroom — designa a hombres transgénero dentro de la cultura. Es identidad Male Figure: compite en categorías masculinas, camina con presentación masculina, y tiene subcategorías propias — Transmale Realness, categorías de Vogue — que reconocen su experiencia específica.",
      "Las guías de Stephaun Elite Wallace son explícitas sobre Transmale Realness: el competidor debe ser hombre trans (FTM), no mujer butch cis ni hombre cis gay. La «realness» evalúa la capacidad de «pasar» como hombre — no como andrógino — en contextos que niegan la existencia de hombres trans negros. Donde la persona esté en su transición social o médica no es relevante para la categoría.",
      "Los hombres trans negros en Ballroom navegan una intersección particularmente hostil: transfobia dentro y fuera de la comunidad LGBTQ+, racismo en espacios trans mayoritariamente blancos, y la invisibilidad histórica de las experiencias trans masculinas negras. Ballroom les ofrece categoría, pista y — cuando la escena funciona con integridad — respeto.",
      "Trans Man compite en MF Sex Siren, MF Body, Transmale Realness, Vogue Femme/Twisters (junto a Butch Queens) y categorías OTA. La inclusión en Vogue Femme/Twisters — donde la presentación puede ser masculina con twist o femenina — reconoce la fluidez expresiva de muchos hombres trans en la pista.",
      "Entender Trans Man en Ballroom requiere rechazar la cisnorma que exige certificados de transición para validar identidad. En la pista de Harlem y en balls que siguen las guías de la House of Luna, un hombre trans es hombre trans porque la comunidad lo reconoce — no porque un documento lo confirme.",
    ],
    canWalk: [
      "face",
      "runway",
      "vogue",
      "realness",
      "sex-siren",
      "body",
      "ota",
      "performance",
    ],
    history: [
      "Los hombres trans han estado en Ballroom desde sus orígenes, aunque la visibilidad histórica favoreció a las Femme Queens — en parte por la epidemia de SIDA que devastó a las mujeres trans negras y las hizo visibles en documentales, y en parte por el sexismo que invisibiliza experiencias trans masculinas.",
      "Transmale Realness se formalizó como categoría en la evolución de Ballroom hacia la especialización identitaria. Antes, los hombres trans competían en categorías BQ o butch sin reconocimiento de su identidad específica — una injusticia que las guías contemporáneas corrigen.",
      "Stephaun Elite Wallace incluyó Trans Man explícitamente en la definición de Male Figure y codificó Transmale Realness con criterios que protegen el espacio trans masculino de la competencia de butch o BQ. La House of Luna adoptó esas guías como estándar.",
      "Hoy, los hombres trans negros compiten en escenas globales con categorías propias y respeto creciente — aunque la lucha por visibilidad continúa. Cada trans man que camina Transmale Realness camina sobre un legado de invisibilidad que Ballroom está aprendiendo, lentamente, a reconocer.",
    ],
    relatedCategories: ["realness", "vogue", "body", "sex-siren"],
  },
  {
    slug: "women",
    name: "Women",
    figure: "FF",
    tagline: "Mujeres cis en Female Figure: rostro, vogue y presencia",
    description: [
      "Women — en la taxonomía de Ballroom — designa específicamente a mujeres cisgénero dentro de Female Figure. Es identidad distinta de Femme Queen (mujer trans) y Drag Queen (hombre cis en fem), con categorías propias: Women's Face, Women's Vogue, categorías FF Sex Siren reservadas para mujeres cis.",
      "Las guías de Stephaun Elite Wallace son precisas: Women's Face es exclusiva para mujeres cis, no para drag queens ni femme queens. Esa distinción protege el espacio de las mujeres cis negras en la pista sin confundirlas con otras identidades bajo el paraguas FF.",
      "Las mujeres cis negras en Ballroom han sido competidoras, mothers, commentatoras y arquitectas de la cultura desde Harlem. Crystal LaBeija era mujer cis; Pepper LaBeija era mujer cis; Dorian Corey era mujer cis. Las mujeres negras cis no son visitantes en Ballroom — son fundadoras, y la categoría Women reconoce su lugar específico dentro de FF.",
      "Women's Vogue es una categoría que exige todos los elementos del voguing — catwalk, duck-walk, hand performance, floor performance, spins/dips — con presentación femenina. Es espacio donde las mujeres cis negras demuestran que el voguing no pertenece solo a hombres gay ni a mujeres trans: pertenece a quien lo domina con chops.",
      "Ser Woman en Ballroom es habitar Female Figure con la especificidad de experiencia cis. No es superioridad ni inferioridad respecto a Femme Queen o Drag Queen — es reconocimiento de que las mujeres cis negras tienen categorías propias porque su experiencia en la pista y en el mundo es distinta, y merece evaluación en sus propios términos.",
    ],
    canWalk: [
      "face",
      "runway",
      "vogue",
      "sex-siren",
      "best-dressed",
      "performance",
    ],
    history: [
      "Las mujeres cis negras estuvieron en los orígenes de Ballroom — no como acompañantes sino como fundadoras, mothers y competidoras. Crystal LaBeija, al fundar la House of LaBeija, era mujer cis negra que creó un universo para personas negras LGBTQ+ expulsadas de concursos drag blancos.",
      "La codificación de Women como identidad separada dentro de FF respondió a la necesidad de las mujeres cis de competir entre ellas sin mezclarse con femme queens o drag queens. Women's Face y Women's Vogue crearon espacios donde la experiencia cis femenina negra era el criterio.",
      "Stephaun Elite Wallace documentó las reglas para Women con la claridad que balls internacionales necesitan. Sus guías — adoptadas por la House of Luna — especifican que Women's Face requiere mujer cis, no drag queen ni femme queen.",
      "Hoy, las mujeres cis negras compiten en escenas globales con categorías propias y respeto. Pero toda Woman que camina una pista camina sobre el legado de Crystal, de Pepper, de Dorian — mujeres negras cis que construyeron Ballroom cuando el mundo les negaba escenario.",
    ],
    relatedCategories: ["face", "runway", "vogue", "sex-siren"],
  },
  {
    slug: "twister",
    name: "Twister",
    figure: "MF",
    tagline: "Butch Queen que voguea fem: la categoría Vogue Femme/Twisters",
    description: [
      "Twister — en la jerga de Ballroom — designa a un Butch Queen que voguea con presentación femenina o con un «twist» de realness masculina. No es identidad separada de BQ sino especialización dentro de la categoría Vogue Femme/Twisters, donde Butch Queens y hombres trans compiten con presentación que puede oscilar entre lo masculino y lo femenino.",
      "La categoría Vogue Femme/Twisters — codificada en las guías de Stephaun Elite Wallace y adoptada por la House of Luna — es exclusiva para Butch Queens y trans men. Requiere todos los elementos del voguing: catwalk, duck-walk, hand performance, floor performance, spins/dips. La presentación puede ser masculina con twist («twisters») o femenina («vogue femme»).",
      "El término «twister» captura la fluidez expresiva del BQ que no se limita a voguing masculino. Un twister puede servir femme con la autoridad de un BQ — combinando la técnica del voguing con la actitud butch queen que caracteriza a la identidad. Es una de las categorías más técnicamente exigentes de Ballroom.",
      "Willi Ninja — aunque no usara el término «twister» — encarnó el espíritu de un BQ que dominaba el voguing en todas sus formas. La categoría Vogue Femme/Twisters honra esa tradición: el BQ negro que no necesita elegir entre masculino y femenino porque domina ambos en la pista.",
      "Entender twister requiere entender que es modalidad de performance dentro de BQ, no identidad nueva. Un Butch Queen que camina Vogue Femme/Twisters sigue siendo BQ — pero en esa categoría específica, su presentación femenina o su twist de realness es lo que los jueces evalúan.",
    ],
    canWalk: ["vogue"],
    history: [
      "Vogue Femme/Twisters como categoría formalizada emerge de la evolución del voguing dentro de Ballroom. A medida que el baile se sofisticó en estilos — Old Way, New Way, Femme, Dramatics — surgió la necesidad de categorías que reconocieran al BQ que voguea fem.",
      "Las guías de Stephaun Elite Wallace especifican que Vogue Femme/Twisters es para BQ y trans men solamente — no para femme queens ni drag queens ni butch. Esa exclusividad protege el espacio de una performance específica: el voguing masculino-femenino del BQ.",
      "La House of Luna adoptó la categoría en sus balls regionales, contribuyendo a la difusión de guías que Harlem codificó. En escenas kiki globales, Vogue Femme/Twisters es una de las categorías más populares y técnicamente exigentes.",
      "Hoy, los twisters — BQ que dominan vogue femme — son referentes de técnica en escenas de todo el planeta. La categoría sigue siendo Male Figure en identidad y femme en performance — la paradoja creativa que solo Ballroom puede sostener.",
    ],
    relatedCategories: ["vogue"],
  },
  {
    slug: "non-binary-ota",
    name: "Non-Binary / OTA",
    figure: "OTA",
    tagline: "Identidades fuera de la binariedad: Open To All en Ballroom",
    description: [
      "Non-Binary / OTA — Open To All — es la expansión identitaria de Ballroom para personas cuya identidad de género no encaja en las categorías binarias de Female Figure o Male Figure. Es identidad OTA: compite en categorías abiertas a todos los géneros y orientaciones, donde lo que importa no es quién eres sino qué traes a la pista.",
      "OTA no es identidad vacía — es reconocimiento explícito de que Ballroom, fundado por personas negras LGBTQ+ en Harlem, siempre fue un espacio de género no conforme. Las categorías FF y MF organizan la competencia especializada; OTA garantiza que quienes no encajan — personas no binarias, gender non-conforming, identidades emergentes — tengan pista propia.",
      "Las categorías OTA — OTA Runway, OTA Bizarre, OTA Old Way vs. New Way, OTA Virgin Vogue, OTA Hand Performance — evalúan talento, creatividad y presencia sin restricción de identidad. Según las guías de Stephaun Elite Wallace, adoptadas por la House of Luna: «Open to all genders/sexualities». La única pregunta es «¿serviste?».",
      "La expansión OTA refleja la evolución de Ballroom hacia la inclusión explícita sin diluir sus raíces negras. Balls en Latinoamérica, Europa y Asia usan OTA para acoger participantes diversos mientras mantienen la cultura y el respeto a los orígenes de Harlem. Pero OTA no es concesión liberal — es extensión de la lógica original de Crystal LaBeija: un espacio para quienes fueron excluidos.",
      "Entender Non-Binary / OTA requiere rechazar la idea de que Ballroom es binario. FF y MF organizan; OTA acoge. Las personas no binarias negras en Ballroom no son «novedad» — son continuación de una tradición queer negra que siempre desafió la binariedad impuesta por la sociedad blanca heteronormativa.",
    ],
    canWalk: [
      "ota",
      "bizarre",
      "performance",
      "hands-performance",
      "best-dressed",
      "labels",
      "runway",
    ],
    history: [
      "OTA como categoría formalizada emerge de la evolución de Ballroom hacia la inclusión explícita en la década de 1990 y 2000. A medida que las categorías FF y MF se especializaron, quedaron fuera personas cuya identidad no encajaba en casillas fijas — y OTA fue la respuesta comunitaria.",
      "Stephaun Elite Wallace codificó OTA con la claridad que escenas globales necesitaban: categorías abiertas a todos los géneros y orientaciones, con evaluación holística de outfit, walk, actitud, creatividad e impacto. La House of Luna adoptó esas guías como estándar.",
      "La expansión Non-Binary dentro de OTA refleja el lenguaje contemporáneo de género — GNC (Gender Non-Conforming), NB (Non-Binary) — aplicado a la arquitectura de Ballroom. Es actualización del vocabulario, no cambio de esencia: Harlem siempre fue queer, siempre fue no binario en la práctica.",
      "Hoy, OTA es la categoría de entrada para muchas personas negras LGBTQ+ que descubren Ballroom fuera de Nueva York. Es puerta de acceso, laboratorio de práctica, y espacio de pertenencia para identidades que FF y MF no pueden contener sin violencia categorizadora.",
    ],
    relatedCategories: ["ota", "bizarre", "performance", "hands-performance"],
  },
  {
    slug: "commentator",
    name: "Commentator",
    tagline: "La voz de la pista: MC, narrador y arquitecto del ball",
    description: [
      "Commentator — en la jerga de Ballroom — es quien sostiene la voz del ball: el MC que anuncia categorías, presenta competidores, lanza shade, lee a la audiencia y mantiene la energía de la noche. No es identidad competitiva — no camina categorías — sino rol esencial sin el cual un ball no funciona.",
      "El commentator es performance verbal en su forma más elevada. Debe conocer la historia de Ballroom, las Houses presentes, las identidades en juego, las reglas de cada categoría y el arte del shade — la crítica sutil disfrazada de cumplido que es lenguaje central de la cultura negra queer. Un buen commentator no solo anuncia — narra, provoca, educa y entretiene.",
      "En Harlem, los commentatoras negras eran — y son — figuras de autoridad en la pista. Su voz marca el ritmo del ball: cuándo sube la tensión, cuándo cae el shade, cuándo la categoría comienza y termina. Pepper LaBeija, con su presencia imponente, encarnaba el espíritu del commentator aunque fuera Mother: autoridad vocal que comanda la sala.",
      "Ser commentator requiere «chops» distintos a los del competidor: inteligencia verbal, timing impecable, conocimiento profundo de la escena, capacidad de leer a la audiencia y de mantener la energía durante horas. Las guías de Stephaun Elite Wallace y la House of Luna reconocen el rol del commentator como parte integral de la arquitectura del ball, aunque no sea categoría competitiva.",
      "El commentator es también educador: en balls donde hay participantes nuevos, la voz del MC explica reglas, identidades y cultura. En escenas kiki globales, el commentator es quien transmite la memoria negra de Harlem a generaciones que no vivieron los orígenes — puente entre historia y presente.",
    ],
    history: [
      "El rol de commentator existe desde los primeros balls de Harlem, aunque no siempre llevaba ese nombre. Alguien tenía que anunciar categorías, presentar Houses y mantener el orden — y esa persona era, casi invariably, una figura negra queer con autoridad reconocida en la escena.",
      "A medida que los balls crecieron en escala y sofisticación, el commentator se profesionalizó. Hoy, los commentatoras más respetados son legends e icons de Ballroom — personas con décadas en la escena cuya voz es tan valorada como cualquier performance en la pista.",
      "Stephaun Elite Wallace y la House of Luna reconocen al commentator como rol esencial en la documentación de guías de balls. Aunque no compite, el commentator es parte de la estructura — como la Mother, el Father, el DJ y los jueces.",
      "Hoy, los commentatoras negras sostienen balls en Harlem, Atlanta, Chicago, Bogotá, São Paulo y decenas de ciudades más. Su voz es el hilo conductor que mantiene viva la cultura negra de Ballroom en cada evento — de kiki a main ball.",
    ],
    relatedCategories: ["performance"],
  },
];
