import type { Legend } from "../types";

export const legends: Legend[] = [
  {
    slug: "crystal-labeija",
    name: "Crystal LaBeija",
    house: "House of LaBeija",
    excerpt:
      "La madre fundadora que dijo «basta» ante el racismo anti-negro y creó un mundo propio para personas negras LGBTQ+.",
    biography:
      "Crystal LaBeija fue la arquitecta espiritual de Ballroom: una drag queen negra de Harlem que transformó la humillación en revolución y fundó la House of LaBeija.",
    biographyParagraphs: [
      "Crystal LaBeija nació en un país que negaba sistemáticamente la belleza negra. En la década de 1960, Harlem era refugio y prisión a la vez: un espacio donde las personas negras podían respirar, pero donde la homofobia, la transfobia y la pobreza seguían siendo el pan de cada día. Crystal entró al mundo del drag y la performance no como hobby, sino como forma de existir en un mundo que la quería invisible.",
      "El documental The Queen (1968) capturó el instante que cambió todo. Crystal participó en el Miss All-America Camp Beauty Pageant, un concurso dominado por drag queens blancas que imponían estándares eurocéntricos de belleza. Fue evaluada con criterios diseñados para excluirla: maquillaje más claro, pelucas lisas, rasgos que imitaran la blancura. Cuando la humillación se volvió insoportable, Crystal habló — y lo que dijo resonó como un grito colectivo de toda una comunidad negra.",
      "«Tengo derecho a mostrar mi color, cariño. Soy bella y sé que soy bella», declaró ante las cámaras. Esas palabras no fueron un desahogo personal: fueron una declaración política de una comunidad entera que había sido silenciada en los espacios queer. Crystal entendió que el problema no era su talento ni su presencia, sino un sistema que premia la blancura y castiga la negritud incluso dentro de la comunidad LGBTQ+.",
      "Poco después, junto a su amiga Lottie, Crystal organizó lo que se considera el primer ball exclusivamente para personas negras LGBTQ+: el First Annual House of LaBeija Ball. No era un concurso alternativo — era la fundación de un universo propio, con sus propias reglas, sus propias madres, sus propios hijos e hijas. Crystal no inventó el baile ni la competencia; inventó el sistema de Houses como lo conocemos: familias elegidas con apellido compartido, donde las personas negras no pedían permiso para ser hermosas — lo exigían.",
      "Como primera Mother reconocida de Ballroom, Crystal estableció un modelo que trasciende generaciones. Las Houses que surgieron después — Xtravaganza, Ninja, Corey, Dupree, Mizrahi — llevan en su ADN la lógica que Crystal articuló: familia cuando el mundo te rechaza, competencia como afirmación de existencia, glamour como acto de resistencia. Cada ball que se celebra hoy en Harlem, Bogotá o París descansa sobre los hombros de Crystal LaBeija.",
      "Crystal murió en 1982, pero su legado no se mide en fechas sino en estructuras vivas. La House of LaBeija sigue siendo una de las casas más respetadas de Ballroom. Pepper LaBeija la sucedió y llevó la llama durante décadas. Generaciones de hijos e hijas negras han llevado el apellido LaBeija en la pista, coronando rostros que el mainstream sigue sin reconocer plenamente. Crystal les dio un apellido, un hogar y un mandato: servir rostro sin pedir permiso.",
      "En Vogue Society, Crystal LaBeija ocupa un lugar central porque sin ella no hay Ballroom como lo conocemos. Fue una mujer negra que convirtió el dolor en arquitectura, la exclusión en pertenencia, la humillación en historia. Su nombre no es un adorno en la memoria de Ballroom — es su cimiento. Toda narrativa sobre voguing, Houses o cultura queer que no comience con Crystal LaBeija está incompleta.",
    ],
  },
  {
    slug: "pepper-labeija",
    name: "Pepper LaBeija",
    house: "House of LaBeija",
    excerpt:
      "La madre imponente que sostuvo la House of LaBeija durante décadas y encarnó la autoridad negra en la pista.",
    biography:
      "Pepper LaBeija fue la Mother de la House of LaBeija que llevó el legado de Crystal al siglo XXI con presencia, sabiduría y un liderazgo que definió generaciones de Ballroom.",
    biographyParagraphs: [
      "Pepper LaBeija heredó de Crystal LaBeija algo más valioso que un apellido: una responsabilidad. Cuando Crystal fundó la House of LaBeija y articuló la visión de Ballroom como refugio para personas negras LGBTQ+, Pepper fue quien convirtió esa visión en institución. Durante décadas, fue la cara visible de una de las casas más antiguas e influyentes de la historia de Ballroom, y lo hizo con una presencia que llenaba cualquier sala antes de que pronunciara una sola palabra.",
      "En la pista, Pepper era imponente. No competía con la fragilidad de quien pide ser vista: entraba con la autoridad de quien sabe que ya lo es. Su walk, su rostro, su capacidad de «servir» en cualquier categoría la convirtieron en referente para generaciones de competidores negros. Pero su grandeza no residía solo en la performance: residía en su capacidad de acoger, entrenar y proteger a los jóvenes que llegaban a la House of LaBeija buscando lo que sus familias biológicas les negaban.",
      "Paris Is Burning (1990) inmortalizó a Pepper en uno de los momentos más elocuentes del documental. Sentada con elegancia, hablando con la calma de quien ha visto pasar generaciones, Pepper explicó la lógica de Ballroom con una claridad que pocas figuras lograron igualar. «Si you shoot an arrow and it goes up in the air», dijo, explicando cómo la fama funciona en la pista y fuera de ella. Esas palabras — filosóficas, directas, profundamente negras — capturaron la sabiduría acumulada de décadas dentro de Ballroom.",
      "Como Mother, Pepper entendió que liderar una House no era un título decorativo. Significaba ofrecer techo cuando era posible, orientación cuando era necesaria, y protección siempre. Muchos jóvenes negros LGBTQ+ que llegaron a la House of LaBeija en los años 70 y 80 lo hicieron desde la calle, desde la precariedad, desde el rechazo familiar. Pepper les dio un apellido, una identidad y un lugar en la pista. Eso no es metáfora: en un contexto de SIDA, violencia policial y pobreza extrema, era supervivencia literal.",
      "Pepper también fue testigo y sobreviviente de la devastación que el SIDA causó en la comunidad negra LGBTQ+ de Harlem. Vio desaparecer a madres, padres, hijos e hijas. Vio cómo Ballroom perdió generaciones enteras de talento, memoria y amor. Y aun así, sostuvo la House of LaBeija. Esa resistencia — continuar acogiendo, continuar compitiendo, continuar honrando a quienes se fueron — es parte esencial de su legado.",
      "La relación entre Pepper y Crystal no fue solo sucesión institucional: fue continuidad de un proyecto negro. Crystal dijo «basta» y fundó un mundo; Pepper lo mantuvo vivo cuando ese mundo enfrentó sus pruebas más duras. Las dos mujeres negras — separadas por generaciones pero unidas por un apellido y una visión — representan la arquitectura matriarcal de Ballroom: madres que construyen, madres que sostienen, madres que no sueltan.",
      "Pepper LaBeija murió en 2003, pero su sombra sigue siendo larga. Cada Mother que lidera una House hoy camina sobre el modelo que Pepper encarnó: autoridad sin crueldad, glamour con propósito, familia elegida como acto político. En la memoria de Ballroom, Pepper no es una figura secundaria detrás de Crystal — es coautora de una historia que sigue escribiéndose en cada ball donde su apellido resuena.",
    ],
  },
  {
    slug: "dorian-corey",
    name: "Dorian Corey",
    house: "House of Corey",
    excerpt:
      "La filósofa de Ballroom cuyas palabras sobre fama, belleza y mortalidad siguen definiendo la cultura negra queer.",
    biography:
      "Dorian Corey fue drag queen legendaria, Mother de la House of Corey y una de las voces intelectuales más agudas que Ballroom haya producido.",
    biographyParagraphs: [
      "Dorian Corey era muchas cosas a la vez: performer, madre de casa, filósofa de la pista, maestra del shade y del reading, y una mujer negra que entendía el mundo con una lucidez que desarmaba. Fundó la House of Corey y construyó una carrera que abarcó décadas dentro de Ballroom, pero su grandeza trasciende los trofeos. Dorian pensaba — y en una cultura donde pensar en voz alta era acto de resistencia, eso la convirtió en una figura única.",
      "En Paris Is Burning, Dorian aparece como la voz más reflexiva del documental. Mientras otros hablan de ambición, de sueños de modelaje, de la emoción de la competencia, Dorian habla de la mortalidad, de la fama efímera, de lo que queda cuando las luces se apagan. Su famosa reflexión — «when it really hits you, that's when you gotta flip the switch» — no es cinismo: es sabiduría negra acumulada en una vida vivida al borde de la exclusión y el brillo.",
      "«I always had hopes of being a big star», dijo Dorian en el documental, antes de desmontar con elegancia la ilusión de la fama mainstream. Explicó cómo las «pursued» se convierten en «pursuers», cómo quien persigue la atención termina persiguiendo a otros, cómo el ciclo de la vanidad consume sin devolver nada duradero. Esas palabras resonaron porque Dorian no las decía desde la envidia ni desde el resentimiento: las decía desde la experiencia de una mujer negra que había visto pasar generaciones de talento sin que el mundo les devolviera lo que merecían.",
      "Como Mother de la House of Corey, Dorian acogió, entrenó y representó a sus hijos e hijas con la misma precisión con la que analizaba la cultura. La House of Corey no fue la más grande ni la más ruidosa, pero fue respetada. Dorian entendía que una House no se mide solo en trofeos sino en la calidad de su legado: en cuántos jóvenes negros LGBTQ+ salieron de su sombra con más herramientas, más confianza y más historia para contar.",
      "Dorian también era maestra del humor negro de Ballroom. Su capacidad de lanzar shade — crítica sutil disfrazada de cumplido — era legendaria. Reading, serving, chopping: Dorian dominaba el lenguaje de la pista no solo como competidora sino como lingüista de una cultura que el mainstream tardaría décadas en reconocer. Cada frase suya en Paris Is Burning es cita; cada análisis suyo es lección.",
      "La historia de Dorian también incluye un epílogo macabro que el mainstream convirtió en morbo: años después de su muerte, en 1993, se encontró un cuerpo momificado en su apartamento, supuestamente de un cliente o conocido de años atrás. Los medios sensacionalizaron el hallazgo, reduciendo la vida de una mujer negra extraordinaria a una anécdota grotesca. La comunidad de Ballroom ha resistido esa narrativa, insistiendo en que Dorian merece ser recordada por su inteligencia, su humor y su legado — no por el morbo de tabloides blancos.",
      "Dorian Corey representa la dimensión intelectual de Ballroom: la cultura negra queer no es solo baile y brillo, es también pensamiento, análisis y filosofía de la supervivencia. En Vogue Society, su voz es recordatorio de que las personas negras dentro de Ballroom no solo crearon un espectáculo — crearon un lenguaje, una ética y una forma de entender el mundo que sigue siendo radical.",
    ],
  },
  {
    slug: "willi-ninja",
    name: "Willi Ninja",
    house: "House of Ninja",
    excerpt:
      "El Grandfather of Vogue que transformó un baile de Harlem en un lenguaje global de expresión negra.",
    biography:
      "Willi Ninja fundó la House of Ninja y es considerado el padre del voguing moderno, llevando el baile de las pistas negras a las pasarelas del mundo.",
    biographyParagraphs: [
      "Willi Ninja nació William Roscoe Leake en 1961, en el seno de una familia negra de Queens, Nueva York. Desde joven mostró un cuerpo que parecía diseñado para el movimiento: largo, flexible, preciso. En las pistas de Harlem, donde el voguing comenzaba a gestarse como forma de expresión negra — inspirado en las poses de las modelos de Vogue y en la estética del haute couture — Willi no solo participaba: dominaba. Pronto le llamarían el «Grandfather of Vogue», y el título no era exageración.",
      "Fundó la House of Ninja y convirtió el voguing en disciplina. Donde otros veían baile espontáneo, Willi veía técnica: líneas limpias, transiciones fluidas, narrativa corporal. Desarrolló el Old Way — poses rígidas, manos que contaban historias, catwalk impecable — y más tarde influenció el New Way, más acrobático y preciso. Su cuerpo era instrumento y su mente era maestro. Entrenó a generaciones de voguers negros que llevaron su técnica a cada rincón de Ballroom.",
      "Lo que distingue a Willi Ninja de muchas figuras de Ballroom es que logró cruzar la frontera entre el underground negro y el mainstream — pero no sin tensiones. Trabajó con Malcolm McLaren en el video «Deep in Vogue» (1989), llevando el baile a audiencias europeas. Enseñó voguing a Madonna para su icónico sencillo «Vogue» (1990), coreografiando movimientos que millones imitarían sin saber su origen. Apareció en videos de Janet Jackson, trabajó con diseñadores de moda, enseñó en academias. Willi demostró que el talento negro de Harlem podía brillar en cualquier escenario.",
      "Pero ese cruce también abrió el debate que sigue vigente: ¿quién se beneficia cuando la cultura negra entra al mainstream? Madonna se hizo millonaria con «Vogue»; Willi Ninja siguió enseñando, compitiendo y sosteniendo la House of Ninja. La visibilidad no siempre se traduce en justicia económica. Willi lo sabía, y sin embargo siguió abriendo puertas para que otros voguers negros pudieran existir fuera de Harlem. Su legado incluye tanto el brillo como la lección sobre apropiación.",
      "Como figura de Ballroom, Willi encarnó una masculinidad negra queer que desafiaba categorías. No era drag queen ni se presentaba como mujer, pero su relación con el movimiento, la moda y la performance lo situaba en el corazón de una cultura creada por personas negras LGBTQ+. La House of Ninja acogió a voguers de todas las identidades, y Willi fue padre, mentor y referente para quienes buscaban dominar un baile que el mundo aún no entendía.",
      "Willi Ninja murió en 2006, a los 45 años, de complicaciones relacionadas con el SIDA — otra víctima de la epidemia que devastó a la comunidad negra LGBTQ+ mientras el mainstream miraba hacia otro lado. Su muerte fue pérdida irreparable para Ballroom, pero su técnica sigue viva: en cada performance de vogue en TikTok, en cada ball en São Paulo o París, en cada joven negro que aprende a «servir» con las manos. Willi no inventó el voguing — eso es un crédito colectivo de Harlem — pero lo codificó, lo enseñó y lo llevó al mundo.",
      "En la memoria de Ballroom, Willi Ninja ocupa un lugar singular: es puente entre la pista negra y la cultura global, entre el Old Way y el New Way, entre la supervivencia underground y la visibilidad mainstream. Vogue Society lo honra no solo como bailarín excepcional sino como arquitecto de un lenguaje corporal que las personas negras crearon y que el mundo entero aprendió a imitar — a menudo sin reconocer de dónde venía.",
    ],
  },
  {
    slug: "angie-xtravaganza",
    name: "Angie Xtravaganza",
    house: "House of Xtravaganza",
    excerpt:
      "La madre latina negra que abrió la puerta de Ballroom a generaciones de jóvenes rechazados por sus familias.",
    biography:
      "Angie Xtravaganza fundó la House of Xtravaganza y fue la primera Mother latina en abrir un espacio de pertenencia para jóvenes negros y latinos LGBTQ+ dentro de Ballroom.",
    biographyParagraphs: [
      "Angie Xtravaganza nació en 1964 como Angel Seguerra, hija de una familia puertorriqueña en Nueva York. Su historia es la de una mujer trans latina negra que construyó familia donde la biológica falló — y que hizo de esa construcción un legado que trasciende generaciones. En la década de 1980, cuando el Ballroom de Harlem ya era institución pero seguía siendo espacio predominantemente negro, Angie fundó la House of Xtravaganza y abrió una puerta que muchos necesitaban.",
      "La House of Xtravaganza fue la primera House latina reconocida en Ballroom, y eso no es detalle menor. Angie entendió que las personas latinas LGBTQ+ — muchas de ellas también negras, muchas rechazadas por familias que las expulsaban por identidad o por orientación — necesitaban un apellido propio, una madre propia, un lugar en la pista. Acogió a decenas de jóvenes: Venus Xtravaganza, José Gutiérrez Xtravaganza, y muchos más que encontraron en Angie lo que sus hogares biológicos les negaron.",
      "Como Mother, Angie combinaba calidez con exigencia. No acogía para decorar: acogía para formar competidores, para construir una House respetada, para demostrar que la excelencia latina negra tenía lugar en Ballroom. La House of Xtravaganza compitió en categorías icónicas — Face, Runway, Vogue — y ganó respeto en una escena donde demostrar «chops» era la única moneda que importaba.",
      "Paris Is Burning capturó a Angie en un momento de vulnerabilidad y fuerza. En el documental, habla de Venus Xtravaganza — una de sus hijas, joven trans negra asesinada durante el rodaje — con un dolor que trasciende la pantalla. Angie llora, recuerda, honra. Es una madre negra perdiendo a su hija en un mundo violento con las mujeres trans negras, y el documental no suaviza esa realidad. La muerte de Venus es parte del legado de la House of Xtravaganza: belleza, talento, promesa — y el costo brutal de ser visible siendo negra y trans en América.",
      "Angie también murió joven: en 1984, a los 27 años, de complicaciones relacionadas con el SIDA. La epidemia arrancó a Ballroom a generaciones enteras de madres, padres, hijos e hijas negras. Angie fue una de las primeras figuras visibles en caer, y su pérdida dejó un vacío que la House of Xtravaganza — y la escena latina de Ballroom — tardó años en procesar. Pero su apellido siguió vivo: José Gutiérrez Xtravaganza, otros miembros, y las casas latinas que surgieron después en Latinoamérica la reconocen como ancestro espiritual.",
      "La intersección de identidad latina y negra en la experiencia de Angie es central para entender Ballroom como movimiento diasporico. Angie no era «latina» en oposición a «negra»: era ambas, en un cuerpo que América racializó de formas complejas y violentas. Su House acogió a jóvenes que compartían esa complejidad — negros, latinos, trans, rechazados — y les dio un apellido que sonaba a glamour y a pertenencia.",
      "En Vogue Society, Angie Xtravaganza representa la expansión del sueño de Crystal LaBeija: Ballroom no es solo para un tipo de persona negra, sino para todas las personas negras LGBTQ+ que necesitan familia. Angie abrió esa puerta para las comunidades latinas negras, y su legado sigue pulsando en cada House latina, en cada ball en Bogotá o São Paulo, en cada joven que lleva el apellido Xtravaganza sabiendo de dónde viene.",
    ],
  },
  {
    slug: "octavia-saint-laurent",
    name: "Octavia Saint Laurent",
    house: "House of Saint Laurent",
    excerpt:
      "La reina de Face que desafió los estándares eurocéntricos y soñó con ser vista en un mundo que ignoraba a las mujeres trans negras.",
    biography:
      "Octavia Saint Laurent fue competidora legendaria en Face y figura central de Paris Is Burning, encarnando la tensión entre Ballroom y el mainstream para las mujeres trans negras.",
    biographyParagraphs: [
      "Octavia Saint Laurent era, en la categoría Face, lo que se llama «untouchable»: una competidora cuyo rostro desafiaba los estándares eurocéntricos de belleza que el mainstream — y muchos espacios queer blancos — imponían. En la pista de Ballroom, Octavia servía rostro con una precisión que dejaba a jueces y audiencias sin palabras. Fuera de la pista, soñaba con algo que el mundo le negaba sistemáticamente: ser modelo.",
      "Paris Is Burning la capturó en su búsqueda. Octavia habla de ir a agencias de modelaje, de ser evaluada con criterios diseñados para excluirla, de la frustración de ser hermosa en Ballroom pero invisible en la industria de la moda. «I'm not trying to prove anything to anybody», dice en un momento, pero la contradicción es el corazón de su historia: Octavia no tenía que probar nada en la pista, pero el mundo exterior exigía pruebas constantes de una mujer trans negra que osaba querer más.",
      "La categoría Face en Ballroom existe precisamente como respuesta a esa exclusión. Cuando los estándares de belleza del mainstream niegan el rostro negro — y especialmente el rostro negro trans — Ballroom crea su propia corona. Octavia fue una de las reinas más memorables de esa categoría. Su presencia en la pista era declaración política disfrazada de competencia: «Mira este rostro. Mira esta belleza negra. Mira lo que ustedes no quieren ver.»",
      "Octavia pertenecía a la House of Saint Laurent, una casa que compitió en las categorías más exigentes de Ballroom. Su relación con la House era de representación: llevaba el apellido en la pista, defendía el honor de la casa, servía como ejemplo para quienes venían después. Pero su ambición trascendía trofeos. Quería portadas de revista, campañas de moda, el reconocimiento que el mainstream reservaba para cuerpos blancos y cisgénero.",
      "Esa tensión — entre el refugio de Ballroom y el rechazo del mundo exterior — define la experiencia de muchas mujeres trans negras en la historia de Ballroom. Dentro de la pista, Octavia era reina. Fuera, era una mujer trans negra en América en los años 80: vulnerable a la violencia, al SIDA, al desprecio social. Paris Is Burning no oculta esa dualidad. Octavia sonríe, compite, sueña — y el documental deja entrever el precio de esos sueños.",
      "Octavia Saint Laurent murió en 2009, después de décadas de vida que incluyeron triunfos en la pista, luchas con la adicción, y la batalla constante por ser vista. Su muerte no recibió la cobertura mediática que merecía una figura de su calibre, pero la comunidad de Ballroom la recordó. En cada competidora de Face que sirve rostro negro hoy, hay ecos de Octavia. En cada mujer trans negra que exige ser reconocida fuera de la pista, hay su legado.",
      "En Vogue Society, Octavia representa la dimensión aspiracional y dolorosa de Ballroom: un espacio donde las personas negras LGBTQ+ pueden ser reyes y reinas, pero que no elimina las barreras del mundo exterior. Su historia es recordatorio de que Ballroom no es escapismo — es supervivencia con glamour, y que el derecho a ser hermosa en la pista no garantiza ser vista afuera. Octavia lo supo, lo vivió, y su memoria exige que sigamos ampliando los espacios donde las mujeres trans negras pueden existir sin negociar su humanidad.",
    ],
  },
  {
    slug: "jose-gutierrez-xtravaganza",
    name: "José Gutiérrez Xtravaganza",
    house: "House of Xtravaganza",
    excerpt:
      "El voguero que llevó el New Way de Harlem al escenario global y enseñó a Madonna a voguear.",
    biography:
      "José Gutiérrez Xtravaganza fue miembro de la House of Xtravaganza que codificó el voguing para el mainstream y demostró que el talento negro latino de Ballroom podía brillar en cualquier escenario.",
    biographyParagraphs: [
      "José Gutiérrez Xtravaganza nació en 1967 en Brooklyn, hijo de una familia dominicana. Su historia es la de un joven latino negro que encontró en Ballroom — y específicamente en la House of Xtravaganza fundada por Angie Xtravaganza — un hogar, un apellido y un camino hacia la maestría. José no llegó al voguing por casualidad: llegó buscando pertenencia, y encontró una disciplina que convertiría en arte y en profesión.",
      "Como miembro de la House of Xtravaganza, José se formó bajo la sombra de Angie y junto a generaciones de voguers que definieron el New Way: un estilo más acrobático, más preciso, más «lethal» en la pista que el Old Way de Willi Ninja. José dominó ese estilo con un cuerpo flexible, una mente rápida y una capacidad de performance que lo distinguía incluso en una House llena de talento. Compitió, ganó respeto, y pronto su nombre trascendió Harlem.",
      "En 1990, la historia de José intersectó con la de la cultura pop global. Madonna preparaba su sencillo «Vogue» y necesitaba bailarines que conocieran el baile auténtico — no una imitación blanca, sino la técnica real de las pistas negras de Nueva York. José fue uno de los voguers que enseñó a Madonna el movimiento, coreografiando y performando en el video icónico que llevaría el voguing a millones de personas que nunca habían oído hablar de Ballroom.",
      "Ese momento es emblemático de la relación entre Ballroom y el mainstream. Por un lado, visibilidad histórica: el talento de José — talento negro, talento latino, talento formado en la House of Xtravaganza — llegó a pantallas de todo el planeta. Por otro lado, el debate sobre apropiación: Madonna se benefició enormemente de una cultura creada por personas negras mientras José y sus contemporáneos seguían navegando las complejidades económicas de ser artistas queer negros en un mundo que rara vez les pagaba lo que merecían. José no desapareció después de «Vogue»: siguió enseñando, performando y representando a la House of Xtravaganza.",
      "José también trabajó en Malcom McLaren's «Deep in Vogue», en el video de Janet Jackson, y en producciones que llevaron el voguing a audiencias internacionales. Se convirtió en maestro: enseñó voguing en academias, en talleres, en contextos donde jóvenes de todo el mundo aprendían un baile creado por personas negras LGBTQ+ en Harlem. Esa labor pedagógica es parte esencial de su legado — no solo performar, sino transmitir.",
      "Como figura latina negra dentro de Ballroom, José encarna la diáspora del movimiento. La House of Xtravaganza fue puerta de entrada para comunidades latinas negras, y José demostró que la excelencia en voguing no tenía nacionalidad única: tenía raíces negras, tenía formación en la pista, tenía respeto ganado con «chops». Para las escenas latinas de Ballroom que surgieron después en Colombia, Brasil o México, José es referente directo.",
      "En Vogue Society, José Gutiérrez Xtravaganza representa el cruce entre pertenencia y trascendencia: un hijo de la House of Xtravaganza que llevó el apellido de Angie al mundo sin olvidar de dónde venía. Su historia es recordatorio de que el talento negro de Ballroom siempre ha sido global — no porque el mainstream lo descubriera, sino porque las personas negras que lo crearon siempre supieron que merecía ser visto. José lo demostró en cada movimiento, en cada clase, en cada performance que enseñó al mundo a voguear.",
    ],
  },
];
